Disable refresh because it fails
Something with quilt:

root@85501cb1c512:~/openwrt# make package/blue-merle/refresh V=sc
WARNING: Makefile 'package/blue-merle/Makefile' has a dependency on 'gl-ui', which does not exist
WARNING: Makefile 'package/blue-merle/Makefile' has a dependency on 'gl-e750-mcu', which does not exist
WARNING: Makefile 'package/blue-merle/Makefile' has a dependency on 'bash', which does not exist
WARNING: Makefile 'package/blue-merle/Makefile' has a dependency on 'coreutils-shred', which does not exist
WARNING: Makefile 'package/blue-merle/Makefile' has a dependency on 'python3', which does not exist
WARNING: Makefile 'package/blue-merle/Makefile' has a dependency on 'python3-pyserial', which does not exist
WARNING: Makefile 'package/blue-merle/Makefile' has a dependency on 'patch', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/boot/kexec-tools/Makefile' has a dependency on 'liblzma', which does not exist
WARNING: Makefile 'package/network/services/lldpd/Makefile' has a dependency on 'libnetsnmp', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a build dependency on 'libpam', which does not exist
make[2]: Entering directory '/root/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/root/openwrt/scripts/config'
make[1]: Entering directory '/root/openwrt'
make[2]: Entering directory '/root/openwrt/package/blue-merle'
The source directory contains no quilt patches.
make[2]: *** [Makefile:151: quilt-check] Error 1
make[2]: Leaving directory '/root/openwrt/package/blue-merle'
time: package/blue-merle/refresh#0.03#0.01#0.04
    ERROR: package/blue-merle failed to build.
make[1]: *** [package/Makefile:120: package/blue-merle/refresh] Error 1
make[1]: Leaving directory '/root/openwrt'
make: *** [/root/openwrt/include/toplevel.mk:232: package/blue-merle/refresh] Error 2
root@85501cb1c512:~/openwrt#